# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hjM0O_mwcBXZhwnFWy0HKw-eqItRwL1V
"""

# Это ячейка кода - нажмите Ctrl+Enter для выполнения
print("Привет, Google Colab!")

# Базовые арифметические операции
a = 15
b = 4

print("Сложение:", a + b)
print("Вычитание:", a - b)
print("Умножение:", a * b)
print("Деление:", a / b)
print("Целочисленное деление:", a // b)
print("Остаток от деления:", a % b)
print("Возведение в степень:", a ** b)

def say_hi (name):
  return f'Привет, {name}! Добро пожаловать в мир программирования!'

print(say_hi("Анна"))
print(say_hi("Иван"))

def define_status(age):
  if age < 18:
    return 'несовершеннолетний'
  elif age < 60:
    return 'взрослый'
  else:
    return 'пенсионер'

age = input('Введите свой возраст:')
print(type(age))
print(f'Ваш возраст: {age}, вы {define_status(int(age))}')

import random

#настройка диапазона и максимального кол-тва попыток
max_attempts = 7
min_range = 1
max_range = 100

secret_number = random.randint(min_range, max_range)
attempts = 1

print(f"Я загадал число от {min_range} до {max_range}")
print(f"У вас есть {max_attempts} попыток!")

while True:

  guess = int(input("Ваше предположение: "))

  if guess == secret_number:
     print(f"\n🎉 Поздравляю! Вы угадали число {secret_number}!")
     print(f"📊 Использовано попыток: {attempts}")
     break
  elif guess < secret_number:
      print("📈 Загаданное число БОЛЬШЕ")
  else:
      print("📉 Загаданное число МЕНЬШЕ")


  if attempts < max_attempts:
    print(f"💡 Осталось попыток: {max_attempts - attempts}")
    attempts +=1
  else:
    print(f"\n💀 Game Over! Вы исчерпали все попытки.")
    print(f"🔢 Загаданное число было: {secret_number}")
    break

